from pathlib import Path
r=Path(__file__).parent
s=Path('/Users/neon/.codex/experiments/soodles44-delivery-20260917/setup.py').read_text().replace('soodles-44','soodles-46').replace('soodles44-delivery-20260917','soodles46-verify-noodle-20260917').replace("'issue':44","'issue':46").replace('fetch_issue(44)','fetch_issue(46)').replace('"issue":44','"issue":46').replace('0cda9c2ee57ed598257048f50829fb36893d3b80','40a3d18785387b57ec482497b62a44805b0e90ad').replace('f2bd849b9523134364ca598df72a4e15fc541ab9','40a3d18785387b57ec482497b62a44805b0e90ad')
a=s.index("task='''");b=s.index("(r/'task.txt')",a)
task='''Implement the P/N guidance of admitted Soodles #46. This is its original Noodle order, created BEFORE implementation. Start HEAD must be clean40a3d18785387b57ec482497b62a44805b0e90ad. Read the exact external issue.json and observer-selection.json under /Users/neon/.codex/experiments/soodles46-verify-noodle-20260917. Use the pinned pstack-create-verification-skill.md there. Existing skills/verify-soodles and execute are patterns. Do not load the unrelated noodles operator runbook.
The child sandbox is known to protect .agents/AGENTS writes. Do not change permissions or repeatedly attempt protected writes. Your concrete implementation deliverable is the COMPLETE proposed bytes of exactly seven admitted files in /Users/neon/.codex/experiments/soodles46-verify-noodle-20260917/draft/ with their repository-relative layout: verify-noodle/SKILL.md and features/README.md, identity-skills.md, admission-recovery.md, order-handoff.md under .agents/skills; existing execute/SKILL.md with one narrow relevant invocation; existing AGENTS.md with one demonstrated routing pointer. No helper scripts or product gates. This is a deliberate supervisor handoff: parent will inspect/apply files in this original worktree only AFTER you naturally exit, then perform final live create/maintenance/acceptance/delivery. Do not edit or commit target source, create worktrees, merge or close. Your draft is real implementation work, not authority or final delivery.
Interview actual Noodle CLI/help and source at /Users/neon/.codex/experiments/noodle78-delivery-20260916/control, pinned ca81f942f478e8e4afcbbce6ca69640867efe753; native binary /Users/neon/.codex/experiments/noodle84-20260917/noodle-merged-ca81 sha2565657c8c3dcaa2491d290a35995c35e4c3d46993955b151f3c75e3bac94476aff. Read nearest command/owner sources and 2-3 existing patterns only. Capture your actual short CLI calls, stdout/stderr/exit in worker-evidence. No production daemon, recovery writes, credential calls or model sessions. Existing own .noodle status may be read only.
The generated skill must have Launch, Doctor, Drive, Evidence, Cleanup, Helpers, Maintenance. Each of THREE feature recipes uses four H2s: Sub-features; How to get to it (user POV); Driving it with the Noodle CLI; Gotchas. Direct links from SKILL to features, independent index. Ground every command in actual help/source. Concrete input contract: supervisor supplies absolute measured binary/source/carrier, admitted subject/worktree or explicit disposable rejected-proposal copy, and external evidence destination. Name missing inputs, provider/owner and existing continuation. Never infer state, permissions or recovery. Consume current next.argv as an argv array; no replay from memory. Valid/admitted/unknown/live proposal refusal is GREEN. No_proposal is not completion. Native macOS evidence does not satisfy Soodles Linux runtime.lock acceptance. Buildinfo may disagree in nested worktrees: compare exact revision/clean flag/digest; no source claim from filename.
Identity/skill feature: read version/build metadata, use actual skills list and verify exact resolved path/digests (resolution is not loading proof). Initial admission feature: stopped owner, exact digest/revision, archival and unchanged canonical checkpoint, disposable fixtures only unless explicitly authorized; use independently accepted #84 recovery observer/fixtures as provided external evidence, do not duplicate its algorithm. Real order/session handoff feature: externally admitted genuine Noodle order before writer; actual raw session/tool/own typed outcome and external recorder wait/exit, process/group absence; original-order completion/provider merge/closure/local cleanup remain distinct. Existing Noodle retry can discard uncommitted work: preserve actual draft/commit before any owner requeue, never invent checkpoint. Do not fabricate a second order for coverage.
Creation must be physically driven by coordinator after applying; label your authoring handoff as pending those stages. Full pstack maintenance then requires one read-only source reviewer per feature and coordinator live drive all features; no new maintenance PR for a clean pass. No claim of cost reduction. No new agent-facing policy/authority flag.
When draft and interview are complete, write a manifest/handoff in worker-evidence with each proposed file digest, exact original order/session/stage, source pointers and unresolved limits. Use actual measured Noodle event emit help/schema to emit ONE matching stage_message completed/blocking false ONLY for the finished authoring/handoff task, clearly state final source application/live maintenance/delivery remain supervisor work. On concrete inability emit blocked. No stage_yield, no exit-code invention. Return immediately after your own typed event. Bounded 720 seconds.'''
s=s[:a]+'task='+repr(task)+'\n'+s[b:]
s=s.replace("'scope':'fresh substantive verification continuation; not retroactive preimplementation order'","'scope':'original order before implementation; explicit protected-skill draft handoff'")
(r/'setup.py').write_text(s)
