from pathlib import Path
import json,hashlib,shutil,subprocess,sys
r=Path(__file__).parent;root=Path('/Users/neon/soodles');source=root/'.worktrees/soodles-44-0-execute';install=r/'installed';install.mkdir()
files=['soodles','soodles.py','issue_admission.py','issue_execution.py','github_reader.py','landing.py','policy/runtime.lock.json','.agents/skills/schedule/SKILL.md','.agents/skills/execute/SKILL.md']
manifest={}
for n in files:
 p=install/n;p.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(source/n,p);manifest[n]=hashlib.sha256(p.read_bytes()).hexdigest()
shutil.copy2('/Users/neon/.codex/experiments/noodle84-20260917/record_process.py',r/'record_process.py')
sys.path.insert(0,str(install));from issue_admission import parse_contract,validate_issue
issue=json.loads((r/'issue.json').read_text());c=parse_contract(issue['body'])
noodle=Path('/Users/neon/.codex/experiments/noodle84-20260917/noodle-merged-ca81');codex=Path('/Users/neon/.codex/packages/standalone/releases/0.153.4-aarch64-apple-darwin/bin/codex')
extra=['-c','default_permissions="agent-default"','-c','approval_policy="never"','-c','model_reasoning_effort="high"','--add-dir',str(root/'.noodle'),'--add-dir',str(r)]
argv=['exec','--skip-git-repo-check','--json','--model','gpt-6-astra',*extra]
task='''Verify the exact clean committed Soodles #44 candidate 0cda9c2ee57ed598257048f50829fb36893d3b80 through this genuine Noodle order. Earlier implementation preceded this order and is disclosed; your substantive job is fresh verification, not an empty delivery marker. No source changes, new commits, provider writes, merge or closure. Read the externally admitted Issue at /Users/neon/.codex/experiments/soodles44-delivery-20260917/issue.json, current execute skill and verify-soodles/features/github-read.md. Run the repository reader and consumer focused tests. Drive ./soodles github issue 44 twice, with a new temporary XDG_CACHE_HOME: actual inherited GH_TOKEN was supplied by the supervisor; never print the environment/token or put it in argv/evidence. Save actual stdout/stderr/exit and elapsed observations under /Users/neon/.codex/experiments/soodles44-delivery-20260917/worker-evidence. Require authenticated HTTP200 then304, identical Issue bytes and exact subject44. Remove only your temporary cache and record cleanup. Run one no-token CLI call (child environment without GH_TOKEN), require structured credential refusal/nonzero; correct refusal is GREEN. Do not mint/rotate credentials or use unauthenticated endpoints. Unexpected quota wait or identity failure is blocked, preserve next; no unchanged retry.
The supervisor owns the fixed external controls and exact-head Linux acceptance already successful for this commit; don't rerun the Linux-only full suite on macOS. Record actual order/session/stage environment identity and skill digest. If tests and live drive succeed, use the measured Noodle binary /Users/neon/.codex/experiments/noodle84-20260917/noodle-merged-ca81 event emit, reading its help/schema, to emit ONE own stage_message with matching actual NOODLE_SESSION_ID, NOODLE_ORDER_ID, integer NOODLE_STAGE_INDEX, outcome completed/blocking false. This denotes your verification stage only. On concrete failure emit blocked/blocking true. Do not emit stage_yield or fill in your exit code; external recorder must wait for your natural exit. Return immediately with one sentence after the typed message. Deadline 480 seconds.'''
(r/'task.txt').write_text(task+'\n');(r/'worker-evidence').mkdir()
envelope={'schema':1,'repository':'ed3c/soodles','issue':44,'body_sha256':hashlib.sha256(issue['body'].encode()).hexdigest(),'body_updated_at':issue['updated_at'],'owner':c['owner'],'write_paths':c['write_paths'],'base_head':'f2bd849b9523134364ca598df72a4e15fc541ab9','execution':{'control_root':str(root),'worktree':'soodles-44-0-execute','order_id':'soodles-44','stage_index':0,'task':task,'source_head':'0cda9c2ee57ed598257048f50829fb36893d3b80','carrier':{'platform':'darwin_arm64','noodle':{'path':str(noodle),'sha256':hashlib.sha256(noodle.read_bytes()).hexdigest()},'codex':{'path':str(codex),'sha256':hashlib.sha256(codex.read_bytes()).hexdigest(),'model':'gpt-6-astra','argv':argv}}}}
validate_issue(issue,envelope);p=r/'execution-envelope.json';p.write_text(json.dumps(envelope,indent=2)+'\n');pin=hashlib.sha256(p.read_bytes()).hexdigest()
prelude='#!'+sys.executable+'\nimport hashlib,os,sys\nfrom pathlib import Path\nroot=Path('+repr(str(install))+')\nmanifest='+repr(manifest)+'\nfor name,digest in manifest.items():\n if hashlib.sha256((root/name).read_bytes()).hexdigest()!=digest:raise SystemExit("changed installed bytes: "+name)\n'
launcher=r/'admission';launcher.write_text(prelude+'if sys.argv[1:] not in (["automatic"],["supervised"]):raise SystemExit("expected route")\nos.execv('+repr(sys.executable)+',['+repr(sys.executable)+',"-B",str(root/"soodles.py"),"issue",sys.argv[1],'+repr(str(p))+','+repr(pin)+'])\n');launcher.chmod(0o755)
provider=r/'provider';provider.mkdir();wrapper=provider/'codex';wrapper.write_text(prelude+'os.execv('+repr(sys.executable)+',['+repr(sys.executable)+',"-B",'+repr(str(r/'record_process.py'))+','+repr(str(r/'process-exits'))+'+"/"+os.environ["NOODLE_SESSION_ID"],"--",'+repr(sys.executable)+',"-B",str(root/"soodles.py"),"issue","worker",'+repr(str(p))+','+repr(pin)+',*sys.argv[1:]])\n');wrapper.chmod(0o755)
adapter=r/'backlog';adapter.write_text(prelude+'import json\nsys.path.insert(0,str(root))\nfrom issue_admission import load_external_envelope,validate_issue\nfrom issue_execution import fetch_issue\ne=load_external_envelope('+repr(str(p))+','+repr(pin)+','+repr(str(root))+')\nif sys.argv[1:]==["sync"]:\n i=fetch_issue(44)\n if i["state"]=="closed":print("")\n else:\n  validate_issue(i,e);print(json.dumps({"id":"soodles-44","title":i["title"],"status":"open","plan":e["execution"]["task"]}))\nelif sys.argv[1:]==["done","soodles-44"]:\n i=fetch_issue(44);validate_issue(i,e,completed=True);print(json.dumps({"readback":"closed/completed","issue":44}))\nelif sys.argv[1:]==["done","schedule"]:print("{}")\nelse:raise SystemExit("unsupported adapter operation")\n');adapter.chmod(0o755)
shutil.copy2(root/'.noodle.toml',r/'previous-noodle.toml');shutil.copy2(root/'.noodle/state.snapshot.json',r/'before.snapshot.json')
config='mode="manual"\n[server]\nenabled=false\n[concurrency]\nmax_concurrency=1\n[routing.defaults]\nprovider="codex"\nmodel="gpt-6-astra"\n[skills]\npaths=['+json.dumps(str(install/'.agents/skills'))+']\n[agents.codex]\npath='+json.dumps(str(provider))+'\nargs='+json.dumps(extra)+'\nrequire_typed_outcome=true\n[adapters.backlog.scripts]\n'
for name in ['sync','add','edit','done']:config+=name+'='+json.dumps(str(adapter)+' '+name)+'\n'
(root/'.noodle.toml').write_text(config)
(r/'selection.json').write_text(json.dumps({'source_head':envelope['execution']['source_head'],'manifest':manifest,'envelope_sha256':pin,'carrier':'native macOS real Noodle/Codex','recorder_sha256':hashlib.sha256((r/'record_process.py').read_bytes()).hexdigest(),'scope':'fresh substantive verification continuation; not retroactive preimplementation order','original39_not_started':True},indent=2)+'\n')
print('Installed fixed supervisor entries and measured envelope44')
